upstream node_backend {
    # In Docker Compose, 'app' is the hostname of your Next.js container
    least_conn;
    server app:3000;
}

# Rate limiting zone
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

# --- HTTP Section (Port 80) ---
server {
    listen 80;
    server_name kielstra-vm.utsc.utoronto.ca;

    # For initial testing (before you have SSL), comment out the 'return 301' 
    # and uncomment the 'location /' block below to test over HTTP.
    
    # Once SSL is ready, uncomment this to force HTTPS:
	location / {
    		proxy_pass http://node_backend;
    		include /etc/nginx/proxy_params; # Use the full path inside the container
	}

}
